//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZapTS.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class LProjectAction
    {
        public long Id { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> ActionId { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Project Project { get; set; }
    }
}
